clc
clear
%load Plot_xtsp.dat;
%load Plot_xtsv.dat;
%load Plot_IC.dat;
%load Plot_DC.dat;
load Plot_Savex.dat;
%load Plot_Savext2.dat;
load Plot_znoise.dat;
load Plot_CM.dat;
load Plot_CD.dat;
%load Plot_Value.dat;
t = 1:3000;
figure(1);
plot(t*0.01, Plot_Savex);
xlabel('Time(s)');
ylabel('Displacement(m)');
grid on;
saveas(1,'Deform.jpg');
%figure(2);
%plot(t*0.01, Plot_xtsv);
%xlabel('Time (seconds)');
%ylabel('Deformation Rate(m)');
%saveas(2,'Deform2.jpg');
%figure(3);
%plot(t*0.01, Plot_IC, t*0.01, Plot_DC);
%figure(4);
%plot(t*0.01, Plot_Savext);
%figure(5);
%plot(t*0.01, Plot_Savext2);
figure(6);
plot(t*0.01, Plot_znoise);
xlabel('Time(s)');
ylabel('Force(N)');
grid on;
saveas(6,'znoise.jpg');
figure(7);
plot(t*0.01, Plot_CD);
xlabel('Time(s)');
ylabel('C_D');
grid on;
saveas(7,'CD.jpg');
figure(8);
plot(t*0.01, Plot_CM);
xlabel('Time(s)');
ylabel('C_M');
grid on;
saveas(8,'CM.jpg');

